data_org_tbl <- data.frame(
  File_name = c("dailyActivity_merged",
           "dailyCalories_merged",
           "dailyIntensities_merged",
           "dailySteps_merged",
           "heartrate_seconds_merged",
           "hourlyCalories_merged",
           "hourlyIntensities_merged",
           "hourlySteps_merged",
           "minuteCaloriesNarrow_merged",
           "minuteCaloriesWide_merged",
           "minuteIntensitiesNarrow_merged",
           "minuteIntensitiesWide_merged",
           "minuteMETsNarrow_merged",
           "minuteSleep_merged",
           "minuteStepsNarrow_merged",
           "minuteStepsWide_merged",
           "sleepDay_merged",
           "weigthLogInfo_merged"),
  Type = c(rep("CSV", 18)),
  Format = c(rep("Long", 9),
             "Wide",
             "Long",
             "Wide",
             rep("Long", 3),
             "Wide",
             rep("Long", 2)),
  Description = c("Daily activity over 31 days for 33 users. Includes: Steps, Distance, Intensities, Calories.",
                  "Daily calories over 31 days for 33 users.",
                  "Daily intensities over 31 days for 33 users. Includes distance and time for 4 different intensity levels.",
                  "Daily steps over 31 days for 33 users.",
                  "Heart rate in intervals of 5 seconds over 31 days for 14 users.",
                  "Hourly calories over 31 days for 33 users.",
                  "Hourly intensities over 31 days for 33 users.",
                  "Hourly steps over 31 days for 33 users.",
                  "Minutely calories over 31 days for 33 users.",
                  "Minutely calories over 31 days for 33 users.",
                  "Minutely intensities over 31 days for 33 users. Binary scale.",
                  "Minutely intensities over 31 days for 33 users. Binary scale.",
                  "Minutely METs* over 31 days for 33 users.",
                  "Minutely sleep score** over 31 days for 24 users.",
                  "Minutely steps over 31 days for 33 users.",
                  "Minutely steps over 31 days for 33 users.",
                  "Daily sleep over 31 days for 24 users.",
                  "Weight information over 31 days for 8 users. Includes weight (kg and pounds), fat, BMI, and whether the report is manual or not."))


type_step_tbl <- data.frame(
  Lifestyle_type = c("Sedentary",
                       "Low active",
                       "Somewhat active",
                       "Active",
                       "Highly active"),
  Steps_per_day = c("< 5000",
            "5000 - 7499",
            "7500 - 9999",
            "10000 - 12499",
            "≥ 12500"))


active_min_tbl <- data.frame(
  Enough_active_minutes = c("Not enough",
             "Enough",
             "More than enough"),
  Fairly_active_minutes = c("0 - 22",
             "22 - 42",
             "≥ 43"),
  Very_active_minutes = c("AND 0 - 11",
           "OR 11 - 21",
           "OR ≥ 22"),
  Health_benefits = c("Low health benefits",
               "Significant health benefits",
               "High health benefits"))


user_days_tbl <- data.frame(
  User_type = c("Sporadic",
           "Moderate",
           "Frequent",
           "Everyday"),
  Days_of_usage = c("0 - 9",
           "10 - 19",
           "20 - 30",
           "31"))


use_min_tbl <- data.frame(
  Usage_group = c("Less than half of the day",
                  "More than half of the day",
                  "Most of the day and night",
                  "All day and night"),
  Minutes_of_usage = c("0-479",
                       "480-959",
                       "960- 1439",
                       "1440"))
